### PR TITLE
support jwt verify without kid

### PR DESCRIPTION
**Pull request by junnplus**
Signed-off-by: Ye Sijun <junnplus@gmail.com>

I remade a PR with minimal changes. Add a new method `find_and_verify`:

```rust
pub fn find_and_verify<ExtraClaims: DeserializeOwned>(
        &self,
        token: &str,
        verifier: fn(&str, &dyn VerificationKey) -> Result<HeaderAndClaims<ExtraClaims>>,
        restrict_kid: bool,
    ) -> Result<HeaderAndClaims<ExtraClaims>>
```

### CODE REVIEW

**Comment by blckngm** [comment]
OK. This is on the right direction.

This `find_and_verify` method is a good abstraction, but a bit too complicated as a public API. I think I will merge this but change to API to this:

```rust
struct JwkSetVerifier {
   ...
   require_kid: bool, // Default true.
}

impl JwkSetVerifier {
    pub fn setRequireKid(&mut self, required: bool) { ... }
}

struct RemoteJwkSetVerifier {
   ...
   require_kid: bool, // Default true.
}

impl RemoteJwkSetVerifier {
    pub fn setRequireKid(&mut self, required: bool) {...}
}
```

**Comment by junnplus** [comment]
@sopium Thanks!

**Comment by blckngm** [comment]
See

https://github.com/sopium/jwtk/commit/acf20c261d587e5c919513fcee7811a013904b00

**Comment by blckngm** [comment]
Released in v0.2.3.

**Pull request merged**
